#!/bin/zsh -eu

youtube-dl --id -- u6dGiANdDNQ
youtube-dl --id -- r5GietxDWgM
youtube-dl --id -- oLRqoHPl6xU
youtube-dl --id -- 2OM3oqQ2RbE
youtube-dl --id -- b2e5xXVYEnY
youtube-dl --id -- zj8wFJxaxVM
youtube-dl --id -- 3-oz1SPWiY4
youtube-dl --id -- -U5SQGQl7ew 
youtube-dl --id -- gkitFhxrYc8
youtube-dl --id -- HsaTjpESyDU
youtube-dl --id -- l0eoLhFTHz4
youtube-dl --id -- UUzTqHLTA4g
youtube-dl --id -- vA9duDV6VFc
youtube-dl --id -- nm2KxtOZOqA
youtube-dl --id -- cusyKShBCi4
youtube-dl --id -- Q01ZWqsU6a8
youtube-dl --id -- auHHRoN7xg4
youtube-dl --id -- 2EoU6EXnPuE
youtube-dl --id -- GB0e1M5p3NU
youtube-dl --id -- zICx1okhU0Y
youtube-dl --id -- b_WbXpc8ASI
youtube-dl --id -- CCTw1j0FL7E
youtube-dl --id -- FPa3kNwnNRk
youtube-dl --id -- r31hPlS1CwE
youtube-dl --id -- Z65lGGMaSFE
youtube-dl --id -- 4WZo39BbE3o
youtube-dl --id -- sf3WSCoqdo8
youtube-dl --id -- F-zT2pI-lnQ
youtube-dl --id -- DXlgdJ34Gnc
youtube-dl --id -- txjZXdu5Xiw
youtube-dl --id -- OXlaho8wayQ
youtube-dl --id -- -cH7TGI6zUk
youtube-dl --id -- bIxeQKzk9-0
youtube-dl --id -- DwEGrNQAj7Q
youtube-dl --id -- vBu6OiSdrds
youtube-dl --id -- yDPZ5Yrn2OI
youtube-dl --id -- cxzukX7Z_1I
youtube-dl --id -- lZPbkfUYavo
youtube-dl --id -- fs-ifFsc8Bg
youtube-dl --id -- _dmpHSznOMk
youtube-dl --id -- 64zoxiMu0p8
youtube-dl --id -- WMeziHjV7Sc
youtube-dl --id -- fmFTmov-K2k
youtube-dl --id -- DKqb-0bBx7E
youtube-dl --id -- 4yzKIYbm6tM
youtube-dl --id -- uGpFQT3Uiig
youtube-dl --id -- 2gqpXl8I7mE
youtube-dl --id -- yyUaFBMwLlA
youtube-dl --id -- ew3CckOY9mc
